# Generated by Django 5.2.7 on 2026-04-28 07:43

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title news')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='slug')),
                ('short_description', models.TextField(max_length=100, verbose_name='short description news')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description news')),
                ('category', models.CharField(choices=[('ANN', 'announcment'), ('CAM', 'campaign'), ('EVE', 'event'), ('MED', 'media'), ('UPD', 'update'), ('EDU', 'educational')], default='ANN', max_length=3, verbose_name='category')),
                ('image_newsroom', models.ImageField(blank=True, null=True, upload_to='pages/newsroom', verbose_name='cover_product')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date time create')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='date time modified')),
                ('is_published', models.BooleanField(default=False, verbose_name='published ?')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='date time create')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'ordering': ['-publish_date', '-date_time_create'],
            },
        ),
    ]
