# Generated by Django 5.2.7 on 2026-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Number of visits'),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='image_newsroom',
            field=models.ImageField(blank=True, null=True, upload_to='pages/newsroom', verbose_name='cover_newsroom'),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date time publish'),
        ),
    ]
