# Generated by Django 5.2.7 on 2026-04-29 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_newsroom_view_count_alter_newsroom_image_newsroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('short_discription', models.CharField(max_length=255, verbose_name='short_discription')),
                ('discription', ckeditor.fields.RichTextField(verbose_name='discription about us')),
            ],
        ),
    ]
