# Generated by Django 5.2.7 on 2026-06-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'aboutus', 'verbose_name_plural': 'aboutus'},
        ),
    ]
