# Generated by Django 5.2.7 on 2025-11-03 15:50

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blogs.category', verbose_name='subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('cover_blog', models.ImageField(blank=True, upload_to='blog/blog_covers/', verbose_name='cover_blog')),
                ('short_description', models.CharField(max_length=100, verbose_name='short_description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_time_create')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='date_time_modified')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.category', verbose_name='category')),
            ],
        ),
    ]
