# Generated by Django 5.2.7 on 2025-11-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name_province')),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city_name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevant_province', to='locations.province', verbose_name='province')),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'cities',
                'unique_together': {('province', 'name')},
            },
        ),
    ]
