# Generated by Django 5.2.7 on 2025-11-11 08:07

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('products', '0010_alter_product_base_price_alter_product_cover_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('national_number', models.CharField(max_length=10, verbose_name='national number')),
                ('exact_address', models.CharField(max_length=700, verbose_name='exact address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('order_notes', ckeditor.fields.RichTextField(verbose_name='order notes')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ_زمان_تغییر یافته')),
                ('city_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='city')),
                ('province_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='products.product', verbose_name='product')),
            ],
        ),
    ]
