# Generated by Django 5.2.7 on 2026-04-24 09:36

import ckeditor.fields
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصول مورد علاقه',
                'verbose_name_plural': 'محصولات مورد علاقه',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت میشود')),
                ('status', models.CharField(choices=[('PEN', 'در انتظار'), ('PAI', 'Paid'), ('CAN', 'Cancelled'), ('RET', 'Returned')], default='PEN', max_length=3, verbose_name='وضعیت')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن همراه')),
                ('national_number', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('exact_address', models.CharField(max_length=700, verbose_name='آدرس دقیق')),
                ('postal_code', models.IntegerField(max_length=10, null=True, verbose_name='کد پستی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('order_notes', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ_زمان_تغییر یافته')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255)),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=255)),
                ('zarinpal_data', models.TextField(blank=True)),
                ('pyment_price', models.CharField(choices=[('PP', 'پرداخت آنلاین'), ('HD', 'درب منزل')], max_length=2, verbose_name='روش پرداخت قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن همراه')),
                ('national_number', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('exact_address', models.CharField(max_length=700, verbose_name='آدرس دقیق')),
                ('postal_code', models.IntegerField(max_length=10, null=True, verbose_name='کد پستی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('order_notes', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ_زمان_تغییر یافته')),
                ('Receive_the_newsletter', models.BooleanField(default=True, verbose_name='خبرنامه را دریافت می کنید؟')),
            ],
        ),
    ]
