# Generated by Django 5.2.7 on 2026-02-05 09:13

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_province'),
        ('orders', '0001_initial'),
        ('products', '0017_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exact_address',
            field=models.CharField(max_length=700, verbose_name='آدرس دقیق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت میشود'),
        ),
        migrations.AlterField(
            model_name='order',
            name='national_number',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش دهید'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='products.product', verbose_name='محصول'),
        ),
    ]
