# Generated by Django 5.2.7 on 2026-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_date_time_create_alter_order_city_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(max_length=10, null=True, verbose_name='postal code'),
        ),
    ]
