# Generated by Django 5.2.7 on 2026-04-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'لیست سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'در انتظار'), ('PAI', 'پرداخت شده است'), ('CAN', 'لغو شد'), ('RET', 'بازگشت')], default='PEN', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
