# Generated by Django 5.2.7 on 2026-02-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Receive_the_newsletter',
            field=models.BooleanField(default=True, verbose_name='Receive the newsletter'),
        ),
    ]
