# Generated by Django 5.2.7 on 2026-05-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarinpal_payment_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='zarinpal payment code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='zarinpal authority'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_data',
            field=models.TextField(blank=True, verbose_name='zarinpal data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='zarinpal ref id'),
        ),
    ]
