# Generated by Django 5.2.7 on 2026-02-06 19:37

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_province'),
        ('orders', '0004_order_receive_the_newsletter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Receive_the_newsletter',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن همراه')),
                ('national_number', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('exact_address', models.CharField(max_length=700, verbose_name='آدرس دقیق')),
                ('postal_code', models.IntegerField(max_length=10, null=True, verbose_name='postal code')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('order_notes', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ_زمان_ایجاد')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ_زمان_تغییر یافته')),
                ('Receive_the_newsletter', models.BooleanField(default=True, verbose_name='Receive the newsletter')),
                ('city_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='شهرستان')),
                ('province_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
