# Generated by Django 5.2.7 on 2026-05-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_zarinpal_payment_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyment_price',
            new_name='payment_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='آتوریتی زرین پال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_data',
            field=models.TextField(blank=True, verbose_name='اطلاعات زرین پال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_payment_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد تایید زرین پال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='رف آی دی زرین پال'),
        ),
    ]
