# Generated by Django 5.2.7 on 2026-02-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_province'),
        ('orders', '0005_remove_order_receive_the_newsletter_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.province', verbose_name='استان'),
        ),
    ]
