# Generated by Django 5.2.7 on 2026-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_pyment_price_order_payment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sms_send',
            field=models.BooleanField(default=False, verbose_name='sms send'),
        ),
    ]
