# Generated by Django 5.2.7 on 2026-06-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_sms_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
