# Generated by Django 5.2.7 on 2026-02-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_profile_city_address_and_more'),
        ('products', '0018_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Receive_the_newsletter',
            field=models.BooleanField(default=True, verbose_name='خبرنامه را دریافت می کنید؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محصول مورد علاقه',
                'verbose_name_plural': 'محصولات مورد علاقه',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
