# Generated by Django 5.2.7 on 2026-02-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_zarinpal_data_order_zarinpal_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pyment_price',
            field=models.CharField(choices=[('PP', 'Pyment Price'), ('HD', 'House Door')], default=1, max_length=2, verbose_name='other pyment price'),
            preserve_default=False,
        ),
    ]
