# Generated by Django 5.2.7 on 2026-03-01 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_pyment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment_price',
            field=models.CharField(choices=[('PP', 'پرداخت آنلاین'), ('HD', 'درب منزل')], max_length=2, verbose_name='روش پرداخت قیمت'),
        ),
    ]
