# Generated by Django 5.2.7 on 2026-04-21 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_id_alter_order_pyment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'در انتظار'), ('PAI', 'پرداخت شده است'), ('CAN', 'لغو شد'), ('RET', 'بازگشت')], default='PEN', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
