# Generated by Django 5.2.7 on 2025-10-20 20:48

import ckeditor.fields
import datetime
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True)),
                ('Width', models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True)),
                ('Height', models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True)),
                ('pot_size', models.CharField(blank=True, max_length=5, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Num', 'Number'), ('Pack', 'Packet')], max_length=4, null=True)),
                ('weight', models.CharField(blank=True, choices=[('GR', 'Gram'), ('KG', 'KiloGram'), ('Ml', 'MilliLiter'), ('L', 'Liter')], max_length=2, null=True)),
                ('ingredients', models.CharField(max_length=250)),
                ('care_tips', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='care tipe')),
                ('usage_instructions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='usage instructions')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVA', 'Available'), ('NON', 'Non-available'), ('SPE', 'Special')], default='AVA', max_length=3)),
                ('inventory', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PAI', 'Paid'), ('CAN', 'Cancelled'), ('RET', 'Returned')], default='PEN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('product_type', models.CharField(choices=[('FL', 'Flower'), ('FER', 'Fertilizer'), ('TOOL', 'Gardening Tool'), ('SEED', 'Seed'), ('SOIL', 'Potting Soil')], max_length=4)),
                ('commodity_status', models.CharField(choices=[('AVA', 'Available'), ('OFS', 'Out_of_stock'), ('PEN', 'Pending'), ('DIS', 'Discontinued')], default='AVA', max_length=3)),
                ('successful_sales_count', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('date_time_create', models.DateTimeField(auto_now_add=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.features')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.inventory')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_release_comment', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('body_comment', ckeditor.fields.RichTextField()),
                ('answer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
            ],
        ),
    ]
