# Generated by Django 5.2.7 on 2026-04-24 09:36

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand_name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_features', models.CharField(max_length=100, verbose_name='name_features')),
                ('Length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length')),
                ('Length_unit', models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Length_unit')),
                ('Width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width')),
                ('Width_unit', models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Width_unit')),
                ('Height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height')),
                ('Height_unit', models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Height_unit')),
                ('pot_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='pot_size')),
                ('number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='number')),
                ('unit_counting', models.CharField(blank=True, choices=[('Num', 'Number'), ('Pack', 'Packet')], max_length=4, null=True, verbose_name='unit_counting')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('GR', 'Gram'), ('KG', 'KiloGram'), ('Ml', 'MilliLiter'), ('L', 'Liter')], max_length=2, null=True, verbose_name='weight_unit')),
                ('ingredients', models.CharField(blank=True, max_length=250, null=True, verbose_name='ingredients')),
                ('care_tips', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='care tipe')),
                ('usage_instructions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='usage instructions')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVA', 'Available'), ('NON', 'Non-available'), ('SPE', 'Special')], default='AVA', max_length=3, verbose_name='status')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True, verbose_name='Address (slug)')),
                ('caver_category', models.ImageField(blank=True, upload_to='category/category_covers/', verbose_name='cover_category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ad Title')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Short description')),
                ('image', models.ImageField(upload_to='slider/category/', verbose_name='caver slide')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Related category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('sku', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='sku')),
                ('product_type', models.CharField(choices=[('FL', 'Flower'), ('FER', 'Fertilizer'), ('TOOL', 'Gardening Tool'), ('SEED', 'Seed'), ('SOIL', 'Potting Soil')], max_length=4, verbose_name='product_type')),
                ('cover_product', models.ImageField(blank=True, null=True, upload_to='product/product_covers/', verbose_name='cover_product')),
                ('commodity_status', models.CharField(choices=[('AVA', 'Available'), ('OFS', 'Out_of_stock'), ('PEN', 'Pending'), ('DIS', 'Discontinued')], default='AVA', max_length=3, verbose_name='commodity_status')),
                ('successful_sales_count', models.PositiveIntegerField(default=0, verbose_name='successful_sales_count')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base_price')),
                ('short_description', models.CharField(max_length=100, verbose_name='short_description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('date_time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_time_create')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='date_time_modified')),
                ('view_count', models.IntegerField(default=0, verbose_name='Number of visits')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.features', verbose_name='features')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_link', to='products.inventory', verbose_name='inventory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='products.product', verbose_name='product_name'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount_percentage')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start_date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='end_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='product_discounts')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_release_comment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_release_comment')),
                ('update_to', models.DateTimeField(auto_now=True, verbose_name='update_to')),
                ('body_comment', ckeditor.fields.RichTextField(verbose_name='body_comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='I recommend purchasing this product ?')),
                ('answer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.comment', verbose_name='answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_and_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_release_question', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_release_question')),
                ('update_to', models.DateTimeField(auto_now=True, verbose_name='update_to')),
                ('body_question', ckeditor.fields.RichTextField(verbose_name='body_question')),
                ('category_question', models.CharField(choices=[('', 'What part do you have a question about?'), ('LAR', 'Log in and register'), ('ORP', 'Order registration process'), ('OT', 'Order tracking'), ('RG', 'Returning goods'), ('DCG', 'Discount codes and gift cards'), ('OS', 'Other cases')], max_length=3, verbose_name='category_question')),
                ('answer_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='products.questions_and_answers', verbose_name='answer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product', verbose_name='Product questions and answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='body_question_answer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.questions_and_answers', verbose_name='answer admin to question product')),
            ],
        ),
    ]
