# Generated by Django 5.2.7 on 2025-10-23 16:45

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Brand_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='subcategories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.comment', verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body_comment',
            field=ckeditor.fields.RichTextField(verbose_name='body_comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_release_comment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_release_comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='update_to',
            field=models.DateTimeField(auto_now=True, verbose_name='update_to'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount_percentage'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='product_discounts'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Height',
            field=models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Length',
            field=models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Width',
            field=models.DecimalField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], decimal_places=2, max_digits=3, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='features',
            name='ingredients',
            field=models.CharField(max_length=250, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='features',
            name='pot_size',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='pot_size'),
        ),
        migrations.AlterField(
            model_name='features',
            name='unit',
            field=models.CharField(blank=True, choices=[('Num', 'Number'), ('Pack', 'Packet')], max_length=4, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='features',
            name='weight',
            field=models.CharField(blank=True, choices=[('GR', 'Gram'), ('KG', 'KiloGram'), ('Ml', 'MilliLiter'), ('L', 'Liter')], max_length=2, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('AVA', 'Available'), ('NON', 'Non-available'), ('SPE', 'Special')], default='AVA', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PAI', 'Paid'), ('CAN', 'Cancelled'), ('RET', 'Returned')], default='PEN', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='order_items'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commodity_status',
            field=models.CharField(choices=[('AVA', 'Available'), ('OFS', 'Out_of_stock'), ('PEN', 'Pending'), ('DIS', 'Discontinued')], default='AVA', max_length=3, verbose_name='commodity_status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_time_create'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date_time_modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.features', verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.inventory', verbose_name='inventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FL', 'Flower'), ('FER', 'Fertilizer'), ('TOOL', 'Gardening Tool'), ('SEED', 'Seed'), ('SOIL', 'Potting Soil')], max_length=4, verbose_name='product_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=100, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='successful_sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='successful_sales_count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
