# Generated by Django 5.2.7 on 2026-05-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='inventory'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
