# Generated by Django 5.2.7 on 2025-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Width',
        ),
        migrations.AddField(
            model_name='features',
            name='Height_number',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='features',
            name='Height_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height_unit'),
        ),
        migrations.AddField(
            model_name='features',
            name='Length_number',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='features',
            name='Length_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length_unit'),
        ),
        migrations.AddField(
            model_name='features',
            name='Width_number',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='features',
            name='Width_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width_unit'),
        ),
        migrations.AddField(
            model_name='features',
            name='unit_number',
            field=models.CharField(blank=True, choices=[('Num', 'Number'), ('Pack', 'Packet')], max_length=4, null=True, verbose_name='unit_number'),
        ),
        migrations.AddField(
            model_name='features',
            name='weight_number',
            field=models.CharField(blank=True, choices=[('GR', 'Gram'), ('KG', 'KiloGram'), ('Ml', 'MilliLiter'), ('L', 'Liter')], max_length=2, null=True, verbose_name='weight_number'),
        ),
        migrations.AlterField(
            model_name='features',
            name='pot_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pot_size'),
        ),
        migrations.AlterField(
            model_name='features',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='features',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weight'),
        ),
    ]
