# Generated by Django 5.2.7 on 2026-06-03 20:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_inventory_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Height_unit',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Length_unit',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Width',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Width_unit',
        ),
        migrations.RemoveField(
            model_name='features',
            name='care_tips',
        ),
        migrations.RemoveField(
            model_name='features',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='features',
            name='number',
        ),
        migrations.RemoveField(
            model_name='features',
            name='pot_size',
        ),
        migrations.RemoveField(
            model_name='features',
            name='unit_counting',
        ),
        migrations.RemoveField(
            model_name='features',
            name='usage_instructions',
        ),
        migrations.RemoveField(
            model_name='features',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='features',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='features',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='discription'),
        ),
        migrations.AddField(
            model_name='features',
            name='image_Technical_specifications',
            field=models.ImageField(blank=True, null=True, upload_to='product/product_covers/', verbose_name='image Technical specifications'),
        ),
        migrations.AddField(
            model_name='features',
            name='short_discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='short_discription'),
        ),
    ]
