# Generated by Django 5.2.7 on 2025-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_features_height_remove_features_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='Height_number',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Length_number',
        ),
        migrations.RemoveField(
            model_name='features',
            name='Width_number',
        ),
        migrations.RemoveField(
            model_name='features',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='features',
            name='unit_number',
        ),
        migrations.RemoveField(
            model_name='features',
            name='weight_number',
        ),
        migrations.AddField(
            model_name='features',
            name='Height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='features',
            name='Length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='features',
            name='Width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='features',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='features',
            name='unit_counting',
            field=models.CharField(blank=True, choices=[('Num', 'Number'), ('Pack', 'Packet')], max_length=4, null=True, verbose_name='unit_counting'),
        ),
        migrations.AddField(
            model_name='features',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('GR', 'Gram'), ('KG', 'KiloGram'), ('Ml', 'MilliLiter'), ('L', 'Liter')], max_length=2, null=True, verbose_name='weight_unit'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Height_unit',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Height_unit'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Length_unit',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Length_unit'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Width_unit',
            field=models.CharField(blank=True, choices=[('Cm', 'SantiMeter'), ('M', 'Meter')], max_length=20, null=True, verbose_name='Width_unit'),
        ),
    ]
