# Generated by Django 5.2.7 on 2025-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_features_height_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='name_features',
            field=models.CharField(default=1, max_length=100, verbose_name='name_features'),
            preserve_default=False,
        ),
    ]
