# Generated by Django 5.2.7 on 2026-06-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_features_height_remove_features_height_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
