# Generated by Django 5.2.7 on 2025-10-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_features_name_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='products.product', verbose_name='product_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_link', to='products.inventory', verbose_name='inventory'),
        ),
    ]
