# Generated by Django 5.2.7 on 2026-06-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover_brand',
            field=models.ImageField(blank=True, null=True, upload_to='brand/cover_brand/', verbose_name='cover brand'),
        ),
    ]
