# Generated by Django 5.2.7 on 2026-06-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_cover_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover_product',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_product', models.ImageField(blank=True, null=True, upload_to='product/product_covers/', verbose_name='cover_product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product_covers')),
            ],
        ),
    ]
