# Generated by Django 5.2.7 on 2025-10-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_inventory_product_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='ingredients',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_link', to='products.inventory', verbose_name='inventory'),
        ),
    ]
