# Generated by Django 5.2.7 on 2026-06-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_cover_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='slug'),
        ),
    ]
