# Generated by Django 5.2.7 on 2025-10-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_product',
            field=models.ImageField(blank=True, upload_to='media/product/product_covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.PositiveIntegerField(verbose_name='base_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_link', to='products.inventory', verbose_name='inventory'),
        ),
    ]
