# Generated by Django 5.2.7 on 2025-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_cover_product_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_product',
            field=models.ImageField(blank=True, upload_to='product/product_covers/', verbose_name='cover_product'),
        ),
    ]
