# Generated by Django 5.2.7 on 2025-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_base_price_alter_product_cover_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caver_category',
            field=models.ImageField(blank=True, upload_to='category/category_covers/', verbose_name='cover_category'),
        ),
    ]
