# Generated by Django 5.2.7 on 2025-12-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ad Title')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Short description')),
                ('image', models.ImageField(upload_to='slider/category/', verbose_name='caver slide')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Related category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
