# Generated by Django 5.2.7 on 2025-12-26 16:58

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_comment_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='I recommend purchasing this product ?'),
        ),
        migrations.CreateModel(
            name='Questions_and_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_release_question', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_release_question')),
                ('update_to', models.DateTimeField(auto_now=True, verbose_name='update_to')),
                ('body_question', ckeditor.fields.RichTextField(verbose_name='body_question')),
                ('answer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.questions_and_answers', verbose_name='answer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product', verbose_name='Product questions and answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
