# Generated by Django 5.2.7 on 2025-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_comment_is_active_questions_and_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_product',
            field=models.ImageField(blank=True, null=True, upload_to='product/product_covers/', verbose_name='cover_product'),
        ),
    ]
