# Generated by Django 5.2.7 on 2026-04-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
