# Generated by Django 5.2.7 on 2026-04-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_and_answers',
            name='category_question',
            field=models.CharField(choices=[('', 'What part do you have a question about?'), ('LAR', 'Log in and register'), ('ORP', 'Order registration process'), ('OT', 'Order tracking'), ('RG', 'Returning goods'), ('DCG', 'Discount codes and gift cards'), ('OS', 'Other cases')], default=1, max_length=3, verbose_name='category_question'),
            preserve_default=False,
        ),
    ]
